// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AdminloginaddtourTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void adminloginaddtour() {
    driver.get("https://www.phptravels.net/admin");
    driver.manage().window().setSize(new Dimension(901, 725));
    driver.findElement(By.name("email")).sendKeys("admin@phptravels.com");
    driver.findElement(By.cssSelector(".input-outlined:nth-child(3) > span")).click();
    driver.findElement(By.name("password")).sendKeys("demoadmi");
    driver.findElement(By.cssSelector(".btn-block > .ladda-label")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-block > .ladda-label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("demoadmin");
    driver.findElement(By.cssSelector(".btn-block > .ladda-label")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-block > .ladda-label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector("#social-sidebar-menu > li:nth-child(9) > a")).click();
    driver.findElement(By.cssSelector("#Tours > li:nth-child(2) > a")).click();
    driver.findElement(By.name("adultprice")).sendKeys("1000");
    driver.switchTo().frame(1);
    driver.findElement(By.cssSelector("html")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".cke_editable"));
      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>A brand new tour</p>'}", element);
    }
    driver.switchTo().defaultContent();
    driver.findElement(By.name("tourstars")).click();
    {
      WebElement dropdown = driver.findElement(By.name("tourstars"));
      dropdown.findElement(By.xpath("//option[. = '4']")).click();
    }
    driver.findElement(By.name("tourhours")).click();
    driver.findElement(By.name("tourhours")).sendKeys("4");
    driver.findElement(By.name("tourdays")).click();
    driver.findElement(By.name("tourdays")).sendKeys("4");
    driver.findElement(By.name("tournights")).click();
    driver.findElement(By.name("tournights")).sendKeys("3");
    {
      WebElement element = driver.findElement(By.cssSelector("#s2id_autogen11 .select2-chosen"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("select2-drop-mask"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".pace-done")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#s2id_locationlist1 .select2-chosen"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#s2id_locationlist1 .select2-chosen"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("select2-drop-mask"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".pace-done")).click();
    driver.findElement(By.name("depositvalue")).click();
    driver.findElement(By.name("depositvalue")).sendKeys("500");
    driver.findElement(By.name("taxvalue")).click();
    driver.findElement(By.name("taxvalue")).sendKeys("250");
    driver.findElement(By.id("add")).click();
    {
      WebElement element = driver.findElement(By.id("add"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".focus")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn:nth-child(4)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".add_button > .btn")).click();
    driver.findElement(By.name("tourname")).click();
    js.executeScript("window.scrollTo(0,84)");
    driver.findElement(By.name("tourname")).sendKeys("oo");
    driver.findElement(By.name("maxadult")).click();
    driver.findElement(By.name("maxadult")).sendKeys("1");
    driver.findElement(By.name("adultprice")).click();
    driver.findElement(By.name("adultprice")).sendKeys("9000");
    driver.findElement(By.id("GENERAL")).click();
    driver.findElement(By.name("tourstars")).click();
    {
      WebElement dropdown = driver.findElement(By.name("tourstars"));
      dropdown.findElement(By.xpath("//option[. = '2']")).click();
    }
    driver.findElement(By.name("tourhours")).click();
    driver.findElement(By.name("tourhours")).sendKeys("1");
    driver.findElement(By.name("tourdays")).click();
    driver.findElement(By.name("tourdays")).sendKeys("2");
    driver.findElement(By.name("tournights")).click();
    driver.findElement(By.name("tournights")).sendKeys("1");
    {
      WebElement element = driver.findElement(By.cssSelector("#s2id_autogen11 .select2-chosen"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#s2id_autogen11 .select2-chosen"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("select2-drop-mask"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".pace-done")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#s2id_locationlist1 .select2-chosen"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("select2-drop-mask"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".pace-done")).click();
    driver.findElement(By.name("depositvalue")).click();
    driver.findElement(By.name("depositvalue")).sendKeys("11");
    driver.findElement(By.name("taxtype")).click();
    driver.findElement(By.name("taxvalue")).click();
    driver.findElement(By.name("taxvalue")).sendKeys("12");
    driver.findElement(By.id("add")).click();
    {
      WebElement element = driver.findElement(By.id("add"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
  }
}
