// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class UserLoginTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void userLogin() {
    driver.get("https://www.phptravels.net/index.php");
    driver.manage().window().setSize(new Dimension(901, 725));
    {
      WebElement element = driver.findElement(By.cssSelector(".dropdown-login > #dropdownCurrency"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".dropdown-login > #dropdownCurrency")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.linkText("Login")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("user@phptravels.com");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("qwerrt");
    driver.findElement(By.cssSelector(".btn-lg")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-lg"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".ink"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".main-wrapper > div:nth-child(1)")).click();
    driver.findElement(By.name("password")).sendKeys("demouser");
    driver.findElement(By.cssSelector(".btn-lg")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ink"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".dropdown-login > #dropdownCurrency")).click();
    driver.findElement(By.cssSelector(".dropdown-login > #dropdownCurrency")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".dropdown-login > #dropdownCurrency"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.linkText("Account")).click();
    {
      WebElement element = driver.findElement(By.linkText("Account"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".nav-item:nth-child(2) > .nav-link")).click();
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("qwerty");
    driver.findElement(By.name("confirmpassword")).click();
    driver.findElement(By.name("confirmpassword")).sendKeys("qwerty");
    driver.findElement(By.cssSelector(".updateprofile")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".updateprofile"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".dropdown-login > #dropdownCurrency")).click();
    driver.findElement(By.cssSelector(".header-top")).click();
    driver.findElement(By.cssSelector(".btn-toggle")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-toggle"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".flights")).click();
    driver.findElement(By.cssSelector(".col-md-1 > .btn-primary")).click();
    js.executeScript("window.scrollTo(0,51)");
    {
      WebElement element = driver.findElement(By.cssSelector(".dropdown-login > #dropdownCurrency"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".btn-toggle")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-toggle"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".dropdown-login > #dropdownCurrency")).click();
    driver.findElement(By.cssSelector(".main-nav > .go-right:nth-child(1) > a")).click();
    driver.findElement(By.cssSelector(".dropdown-login > #dropdownCurrency")).click();
    driver.findElement(By.cssSelector(".btn-toggle")).click();
    driver.findElement(By.cssSelector(".go-right:nth-child(3) > a")).click();
    driver.findElement(By.linkText("Dubai Special Packages")).click();
    driver.findElement(By.cssSelector(".dropdown-login > #dropdownCurrency")).click();
    driver.findElement(By.linkText("Account")).click();
    driver.findElement(By.cssSelector(".btn-toggle")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-toggle"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".tours")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".select2-default > .select2-chosen"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".select2-focused"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".with-waypoint-sticky")).click();
    {
      WebElement element = driver.findElement(By.id("select2-drop-mask"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#tourtype_chosen span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".with-waypoint-sticky")).click();
    driver.findElement(By.cssSelector(".ftab-inner .col-md-2 > .btn")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ftab-inner .col-md-2 > .btn"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Hong Kong Island Tour")).click();
    {
      WebElement element = driver.findElement(By.linkText("Hong Kong Island Tour"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".wishtext")).click();
    assertThat(driver.switchTo().alert().getText(), is("Do you want to add it to wishlist ?"));
    driver.switchTo().alert().dismiss();
    driver.findElement(By.cssSelector(".wishtext")).click();
    assertThat(driver.switchTo().alert().getText(), is("Do you want to add it to wishlist ?"));
    driver.switchTo().alert().accept();
    driver.findElement(By.cssSelector(".btn-toggle")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-toggle"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".dropdown-login > #dropdownCurrency")).click();
    driver.findElement(By.linkText("Account")).click();
    {
      WebElement element = driver.findElement(By.linkText("Account"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".nav-item > .active"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".nav-item:nth-child(3) > .nav-link")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".nav-item:nth-child(3) > .nav-link"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
  }
}
